### ISSUE TITLE
Add detailed installation instructions

### ISSUE THREAD

**Issue by mukul-mehta** [SUSE/phoebe#31]
I tried setting up phoebe on a new Tumbleweed VM today and I had a couple of issues with missing dependencies:

1.  `libnl-3.0` was missing
2. `json-c` was missing
3. I had a couple of issues with `cmocka`. After building from source, I tried building phoebe and ran into linker issues. Installing  RPMs from rpmfind fixed the issue. Could somebody confirm if this is the expected way to fulfil the cmocka dependency, I haven't used it before and I was wondering if I was missing something in the process?

It'd be great to have a bit more detailed instructions for building the repository. I could create an `INSTALL.md` file to add more instructions to build on Tumbleweed to begin with

**Comment by mvarlese** [comment]
Dear @mukul-mehta ,

Our CI is building the code against all recent Leap versions plus Tumbleweed without issues. What you may have experienced is probably missing devel dependencies on your installation. 

Now, considered I understand this could be a situation others could bump into I would welcome a PR for a DEPENDENCIES.md which depicts in details *all* the dependencies required to successfully build Phoebe.

When doing that, please, make sure you have different sections per latest Leap distros, eg. Leap15.3, Leap15.2, Leap15.1, TW and possibly some other distributions, ie. Ubuntu, etc.

We already explain how to build the code in our README.md so let's not duplicate information across multiple files, please.


HTH,
Marco

**Comment by mvarlese** [comment]
To facilitate you with that:

TW: 
zypper -n in gcc clang make libnetlink-devel libnl3-devel libjson-c-devel meson ethtool python3 python3-devel python3-cffi git valgrind libcmocka-devel

LEAP 15.2:
zypper -n in gcc clang make libnetlink-devel libnl3-devel libjson-c-devel meson ethtool python3 python3-devel python3-cffi git valgrind libcmocka-devel


Thanks.

**Comment by mukul-mehta** [comment]
@mvarlese Yes, the issues were due to missing devel dependencies on my installation

Sure, it sounds like a good idea to create a `DEPENDENCIES.md` file that lists installation instructions for TW, Leap and possibly Debian based distributions. I'll create one and send a PR for it

Thank you for the help

**Comment by mvarlese** [comment]
@mukul-mehta thank you. I look forward to your PR.

**Comment by mvarlese** [comment]
PR pushed to master

**Comment by mukul-mehta** [comment]
@mvarlese Sorry for the delay in creating a PR, I was under some load from college. Thank you for adding it, I'll add instructions for Debian/Ubuntu 😄
